language: ruby
rvm:
  - 2.1.5

before_script:
  - git clone https://gist.github.com/6179925.git -b v2.0 kalibro_install
  - pushd kalibro_install
    # Remove bugged libzmq3 package, see https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
  - sudo apt-get remove libzmq3
  - bash install.sh
  - popd
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:setup
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile

script:
  - bundle exec rake spec
  - bundle exec rake konacha:run
  - bundle exec rake cucumber

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
